deck_config_uuid: 495b7494-1b0b-11ee-8ac9-c5d2cf109b08
deck_configurations:
- __type__: DeckConfig
  autoplay: true
  buryInterdayLearning: true
  crowdanki_uuid: 495b7494-1b0b-11ee-8ac9-c5d2cf109b08
  dyn: false
  interdayLearningMix: 0
  lapse:
    delays:
    - 10.0
    leechAction: 1
    leechFails: 8
    minInt: 1
    mult: 0.0
  maxTaken: 60
  name: AnkiLangs
  new:
    bury: true
    delays:
    - 1.0
    - 10.0
    initialFactor: 2500
    ints:
    - 1
    - 4
    - 0
    order: 1
    perDay: 20
  newGatherPriority: 0
  newMix: 0
  newPerDayMinimum: 0
  newSortOrder: 0
  replayq: true
  rev:
    bury: true
    ease4: 1.3
    hardFactor: 1.2
    ivlFct: 1.0
    maxIvl: 36500
    perDay: 200
  reviewOrder: 0
  timer: 0
dyn: 0
extendNew: 0
extendRev: 0
md: true
newLimit: null
newLimitToday: null
reviewLimit: null
reviewLimitToday: null
